//tealium universal tag - utag.197 ut4.0.202009070229, Copyright 2020 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.map={};u.extend=[];u.checkForDuplicateCalls=function(){var session_match;if(utag.data['cp.utag_main_ses_id']){session_match=utag.data['cp.utag_main_ses_id']+";exp-session";if(typeof utag.data['cp.utag_main_krux_sync_session']==="undefined"){utag.loader.SC("utag_main",{"krux_sync_session":session_match});}else{if(utag.data['cp.utag_main_krux_sync_session']===utag.data['cp.utag_main_ses_id']){utag.DB(u.id+"Same session detected, duplicate Krux Cookie Matching vdata call not sent.");return;}else{utag.loader.SC("utag_main",{"krux_sync_session":session_match});}}}};u.determineKruxNamespace=function(){var key,namespace="";if(typeof Krux!=="undefined"&&typeof Krux.ns!=="undefined"){for(key in Krux.ns){if(Krux.ns.hasOwnProperty(key)&&typeof Krux.ns[key].nsName!=="undefined"){namespace=Krux.ns[key].nsName;}}}
return namespace;};u.captureKruxKUID=function(){var key,kuid="";if(window.localStorage&&localStorage.getItem(("kx"+u.data.krux_namespace+"_kuid"))){kuid=localStorage.getItem(("kx"+u.data.krux_namespace+"_kuid"));}else if(typeof Krux!=="undefined"&&typeof Krux.ns!=="undefined"){for(key in Krux.ns){if(Krux.ns.hasOwnProperty(key)&&typeof Krux.ns[key].nsName!=="undefined"){kuid=Krux.ns[u.data.krux_namespace]("get","user");}}}
return kuid;};u.matchKruxKUID=function(capture,wait_time,max_attempts,query_params){u.data.kuid=capture();if(u.data.kuid){u.checkForDuplicateCalls();query_params.push("krux_id"+u.data.kvp_delim+u.data.kuid);u.loader({"type":"img","src":u.data.base_url+query_params.join(u.data.qsp_delim)});}else{var count=0;var timer=setInterval(function(){u.data.kuid=capture();if(u.data.kuid){u.checkForDuplicateCalls();query_params.push("krux_id"+u.data.kvp_delim+u.data.kuid);u.loader({"type":"img","src":u.data.base_url+query_params.join(u.data.qsp_delim)});clearInterval(timer);}else{count++;if(count>max_attempts){utag.DB(u.id+": Krux Cookie Matching Service vdata sync call not fired: Unable to acquire Krux ID");clearInterval(timer);}}},wait_time);}}
u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:197");utag.DB(b);var c,d,e,f,query_params=[];u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"https://datacloud.tealiumiq.com/vdata/i.gif?","tealium_account":"","tealium_profile":"","krux_namespace":"seekanz","attempts":2,"wait_time":2000,"kuid":"","iab_v11_compliance":true,"iab_v20_compliance":true,"tc_string":""};utag.DB("send:197:EXTENSIONS");utag.DB(b);for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:197:MAPPINGS");utag.DB(u.data);if((u.data.iab_v11_compliance===true||u.data.iab_v11_compliance==="true")&&typeof __cmp==="function"){__cmp("getVendorConsents",[522],function(consents,is_successful){var consented_to_tealium=consents.vendorConsents[522];var consented_to_purposes=consents.purposeConsents[1]&&consents.purposeConsents[2]&&consents.purposeConsents[3]&&consents.purposeConsents[5];if(consented_to_tealium&&consented_to_purposes){execute_send();}else{utag.DB("Detected that consent was not granted for Tealium and/or its listed purposes. Aborting tag "+u.id+".");}});}else if(u.data.iab_v20_compliance===true||u.data.iab_v20_compliance==="true"){if(typeof __tcfapi==="function"){__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.tc_string+="1";}else if(tcData.gdprApplies===false){u.data.tc_string+="0";}else{u.data.tc_string+=String(tcData.gdprApplies);}
u.data.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}else{var frame=window;var cmpFrame;var cmpCallbacks={};while(frame){try{if(frame.frames["__tcfapiLocator"]){cmpFrame=frame;break;}}catch(error){utag.DB(error);}
if(frame===window.top){break;}
frame=frame.parent;}
if(!cmpFrame){execute_send();}else{window.__tcfapi=function(cmd,version,callback,arg){var callId=String(Math.random());var msg={__tcfapiCall:{command:cmd,parameter:arg,version:version,callId:callId}};cmpCallbacks[callId]=callback;cmpFrame.postMessage(msg,"*");};window.tealiumiabPostMessageHandler=function(event){var json={};try{json=typeof event.data==="string"?JSON.parse(event.data):event.data;}catch(error){utag.DB(error);}
var payload=json.__tcfapiReturn;if(payload){if(typeof cmpCallbacks[payload.callId]==="function"){cmpCallbacks[payload.callId](payload.returnValue,payload.success);cmpCallbacks[payload.callId]=null;}}};window.addEventListener("message",tealiumiabPostMessageHandler,false);__tcfapi("getTCData",2,function(tcData,success){if(success){u.data.tc_string+="gdpr=";if(tcData.gdprApplies===true){u.data.tc_string+="1";}else if(tcData.gdprApplies===false){u.data.tc_string+="0";}else{u.data.tc_string+=String(tcData.gdprApplies);}
u.data.tc_string+="&gdpr_consent="+tcData.tcString;execute_send();}});}}}else{execute_send();}
function execute_send(){if(b['cp.utag_main_krux_sync_session']===b['cp.utag_main_ses_id']){utag.DB("Same session detected, duplicate Krux Cookie Matching vdata call not sent.");return;}
u.data.tealium_account=u.data.tealium_account||utag.cfg.utid.split("/")[0];u.data.tealium_profile=u.data.tealium_profile||utag.cfg.utid.split("/")[1];if(u.data.tc_string){u.data.base_url+=u.data.tc_string+"&";}
query_params.push("tealium_cookie_sync"+u.data.kvp_delim+"true");query_params.push("tealium_account"+u.data.kvp_delim+u.data.tealium_account);query_params.push("tealium_profile"+u.data.kvp_delim+u.data.tealium_profile);query_params.push("tealium_vid"+u.data.kvp_delim+b["cp.utag_main_v_id"]);u.data.attempts=parseInt(u.data.attempts)||2;u.data.wait_time=parseInt(u.data.wait_time)||2000;u.data.krux_namespace=u.data.krux_namespace||u.determineKruxNamespace();if(!u.data.krux_namespace){utag.DB(u.id+": Tag not fired: Required attribute krux_namespace not populated");return;}
u.matchKruxKUID(u.captureKruxKUID,u.data.wait_time,u.data.attempts,query_params);utag.DB("send:197:COMPLETE");}}};utag.o[loader].loader.LOAD(id);}("197","seek.houston"));}catch(error){utag.DB(error);}
